// Code generated by go-swagger; DO NOT EDIT.

package sessions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAPIV1SessionsByIDGetParams creates a new APIV1SessionsByIDGetParams object
// with the default values initialized.
func NewAPIV1SessionsByIDGetParams() *APIV1SessionsByIDGetParams {
	var ()
	return &APIV1SessionsByIDGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAPIV1SessionsByIDGetParamsWithTimeout creates a new APIV1SessionsByIDGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAPIV1SessionsByIDGetParamsWithTimeout(timeout time.Duration) *APIV1SessionsByIDGetParams {
	var ()
	return &APIV1SessionsByIDGetParams{

		timeout: timeout,
	}
}

// NewAPIV1SessionsByIDGetParamsWithContext creates a new APIV1SessionsByIDGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewAPIV1SessionsByIDGetParamsWithContext(ctx context.Context) *APIV1SessionsByIDGetParams {
	var ()
	return &APIV1SessionsByIDGetParams{

		Context: ctx,
	}
}

// NewAPIV1SessionsByIDGetParamsWithHTTPClient creates a new APIV1SessionsByIDGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAPIV1SessionsByIDGetParamsWithHTTPClient(client *http.Client) *APIV1SessionsByIDGetParams {
	var ()
	return &APIV1SessionsByIDGetParams{
		HTTPClient: client,
	}
}

/*APIV1SessionsByIDGetParams contains all the parameters to send to the API endpoint
for the Api v1 sessions by Id get operation typically these are written to a http.Request
*/
type APIV1SessionsByIDGetParams struct {

	/*ID
	  Session ID

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the Api v1 sessions by Id get params
func (o *APIV1SessionsByIDGetParams) WithTimeout(timeout time.Duration) *APIV1SessionsByIDGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Api v1 sessions by Id get params
func (o *APIV1SessionsByIDGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Api v1 sessions by Id get params
func (o *APIV1SessionsByIDGetParams) WithContext(ctx context.Context) *APIV1SessionsByIDGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Api v1 sessions by Id get params
func (o *APIV1SessionsByIDGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Api v1 sessions by Id get params
func (o *APIV1SessionsByIDGetParams) WithHTTPClient(client *http.Client) *APIV1SessionsByIDGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Api v1 sessions by Id get params
func (o *APIV1SessionsByIDGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the Api v1 sessions by Id get params
func (o *APIV1SessionsByIDGetParams) WithID(id int64) *APIV1SessionsByIDGetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the Api v1 sessions by Id get params
func (o *APIV1SessionsByIDGetParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *APIV1SessionsByIDGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
