// Code generated by go-swagger; DO NOT EDIT.

package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// APIV1WebhooksPostReader is a Reader for the APIV1WebhooksPost structure.
type APIV1WebhooksPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *APIV1WebhooksPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewAPIV1WebhooksPostCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewAPIV1WebhooksPostBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewAPIV1WebhooksPostUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewAPIV1WebhooksPostForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewAPIV1WebhooksPostConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAPIV1WebhooksPostCreated creates a APIV1WebhooksPostCreated with default headers values
func NewAPIV1WebhooksPostCreated() *APIV1WebhooksPostCreated {
	return &APIV1WebhooksPostCreated{}
}

/*APIV1WebhooksPostCreated handles this case with default header values.

Webhook created
*/
type APIV1WebhooksPostCreated struct {
	Payload int32
}

func (o *APIV1WebhooksPostCreated) Error() string {
	return fmt.Sprintf("[POST /api/v1/Webhooks][%d] apiV1WebhooksPostCreated  %+v", 201, o.Payload)
}

func (o *APIV1WebhooksPostCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAPIV1WebhooksPostBadRequest creates a APIV1WebhooksPostBadRequest with default headers values
func NewAPIV1WebhooksPostBadRequest() *APIV1WebhooksPostBadRequest {
	return &APIV1WebhooksPostBadRequest{}
}

/*APIV1WebhooksPostBadRequest handles this case with default header values.

Bad Request
*/
type APIV1WebhooksPostBadRequest struct {
	Payload APIV1WebhooksPostBadRequestBody
}

func (o *APIV1WebhooksPostBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v1/Webhooks][%d] apiV1WebhooksPostBadRequest  %+v", 400, o.Payload)
}

func (o *APIV1WebhooksPostBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAPIV1WebhooksPostUnauthorized creates a APIV1WebhooksPostUnauthorized with default headers values
func NewAPIV1WebhooksPostUnauthorized() *APIV1WebhooksPostUnauthorized {
	return &APIV1WebhooksPostUnauthorized{}
}

/*APIV1WebhooksPostUnauthorized handles this case with default header values.

Unauthorized
*/
type APIV1WebhooksPostUnauthorized struct {
}

func (o *APIV1WebhooksPostUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v1/Webhooks][%d] apiV1WebhooksPostUnauthorized ", 401)
}

func (o *APIV1WebhooksPostUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAPIV1WebhooksPostForbidden creates a APIV1WebhooksPostForbidden with default headers values
func NewAPIV1WebhooksPostForbidden() *APIV1WebhooksPostForbidden {
	return &APIV1WebhooksPostForbidden{}
}

/*APIV1WebhooksPostForbidden handles this case with default header values.

Forbidden
*/
type APIV1WebhooksPostForbidden struct {
}

func (o *APIV1WebhooksPostForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v1/Webhooks][%d] apiV1WebhooksPostForbidden ", 403)
}

func (o *APIV1WebhooksPostForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAPIV1WebhooksPostConflict creates a APIV1WebhooksPostConflict with default headers values
func NewAPIV1WebhooksPostConflict() *APIV1WebhooksPostConflict {
	return &APIV1WebhooksPostConflict{}
}

/*APIV1WebhooksPostConflict handles this case with default header values.

Conflict
*/
type APIV1WebhooksPostConflict struct {
	Payload int32
}

func (o *APIV1WebhooksPostConflict) Error() string {
	return fmt.Sprintf("[POST /api/v1/Webhooks][%d] apiV1WebhooksPostConflict  %+v", 409, o.Payload)
}

func (o *APIV1WebhooksPostConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*APIV1WebhooksPostBadRequestBody API v1 webhooks post bad request body
swagger:model APIV1WebhooksPostBadRequestBody
*/
type APIV1WebhooksPostBadRequestBody map[string]string

// Validate validates this API v1 webhooks post bad request body
func (o APIV1WebhooksPostBadRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
