// Code generated by go-swagger; DO NOT EDIT.

package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAPIV1WebhooksByIDDeleteParams creates a new APIV1WebhooksByIDDeleteParams object
// with the default values initialized.
func NewAPIV1WebhooksByIDDeleteParams() *APIV1WebhooksByIDDeleteParams {
	var ()
	return &APIV1WebhooksByIDDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAPIV1WebhooksByIDDeleteParamsWithTimeout creates a new APIV1WebhooksByIDDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAPIV1WebhooksByIDDeleteParamsWithTimeout(timeout time.Duration) *APIV1WebhooksByIDDeleteParams {
	var ()
	return &APIV1WebhooksByIDDeleteParams{

		timeout: timeout,
	}
}

// NewAPIV1WebhooksByIDDeleteParamsWithContext creates a new APIV1WebhooksByIDDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewAPIV1WebhooksByIDDeleteParamsWithContext(ctx context.Context) *APIV1WebhooksByIDDeleteParams {
	var ()
	return &APIV1WebhooksByIDDeleteParams{

		Context: ctx,
	}
}

// NewAPIV1WebhooksByIDDeleteParamsWithHTTPClient creates a new APIV1WebhooksByIDDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAPIV1WebhooksByIDDeleteParamsWithHTTPClient(client *http.Client) *APIV1WebhooksByIDDeleteParams {
	var ()
	return &APIV1WebhooksByIDDeleteParams{
		HTTPClient: client,
	}
}

/*APIV1WebhooksByIDDeleteParams contains all the parameters to send to the API endpoint
for the Api v1 webhooks by Id delete operation typically these are written to a http.Request
*/
type APIV1WebhooksByIDDeleteParams struct {

	/*ID*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the Api v1 webhooks by Id delete params
func (o *APIV1WebhooksByIDDeleteParams) WithTimeout(timeout time.Duration) *APIV1WebhooksByIDDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Api v1 webhooks by Id delete params
func (o *APIV1WebhooksByIDDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Api v1 webhooks by Id delete params
func (o *APIV1WebhooksByIDDeleteParams) WithContext(ctx context.Context) *APIV1WebhooksByIDDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Api v1 webhooks by Id delete params
func (o *APIV1WebhooksByIDDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Api v1 webhooks by Id delete params
func (o *APIV1WebhooksByIDDeleteParams) WithHTTPClient(client *http.Client) *APIV1WebhooksByIDDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Api v1 webhooks by Id delete params
func (o *APIV1WebhooksByIDDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the Api v1 webhooks by Id delete params
func (o *APIV1WebhooksByIDDeleteParams) WithID(id int32) *APIV1WebhooksByIDDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the Api v1 webhooks by Id delete params
func (o *APIV1WebhooksByIDDeleteParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *APIV1WebhooksByIDDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
