// Code generated by go-swagger; DO NOT EDIT.

package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// APIV1WebhooksDeleteReader is a Reader for the APIV1WebhooksDelete structure.
type APIV1WebhooksDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *APIV1WebhooksDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewAPIV1WebhooksDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewAPIV1WebhooksDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewAPIV1WebhooksDeleteUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewAPIV1WebhooksDeleteForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewAPIV1WebhooksDeleteNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAPIV1WebhooksDeleteNoContent creates a APIV1WebhooksDeleteNoContent with default headers values
func NewAPIV1WebhooksDeleteNoContent() *APIV1WebhooksDeleteNoContent {
	return &APIV1WebhooksDeleteNoContent{}
}

/*APIV1WebhooksDeleteNoContent handles this case with default header values.

Webhooks deleted
*/
type APIV1WebhooksDeleteNoContent struct {
}

func (o *APIV1WebhooksDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/Webhooks][%d] apiV1WebhooksDeleteNoContent ", 204)
}

func (o *APIV1WebhooksDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAPIV1WebhooksDeleteBadRequest creates a APIV1WebhooksDeleteBadRequest with default headers values
func NewAPIV1WebhooksDeleteBadRequest() *APIV1WebhooksDeleteBadRequest {
	return &APIV1WebhooksDeleteBadRequest{}
}

/*APIV1WebhooksDeleteBadRequest handles this case with default header values.

Bad Request
*/
type APIV1WebhooksDeleteBadRequest struct {
	Payload APIV1WebhooksDeleteBadRequestBody
}

func (o *APIV1WebhooksDeleteBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/Webhooks][%d] apiV1WebhooksDeleteBadRequest  %+v", 400, o.Payload)
}

func (o *APIV1WebhooksDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAPIV1WebhooksDeleteUnauthorized creates a APIV1WebhooksDeleteUnauthorized with default headers values
func NewAPIV1WebhooksDeleteUnauthorized() *APIV1WebhooksDeleteUnauthorized {
	return &APIV1WebhooksDeleteUnauthorized{}
}

/*APIV1WebhooksDeleteUnauthorized handles this case with default header values.

Unauthorized
*/
type APIV1WebhooksDeleteUnauthorized struct {
}

func (o *APIV1WebhooksDeleteUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/Webhooks][%d] apiV1WebhooksDeleteUnauthorized ", 401)
}

func (o *APIV1WebhooksDeleteUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAPIV1WebhooksDeleteForbidden creates a APIV1WebhooksDeleteForbidden with default headers values
func NewAPIV1WebhooksDeleteForbidden() *APIV1WebhooksDeleteForbidden {
	return &APIV1WebhooksDeleteForbidden{}
}

/*APIV1WebhooksDeleteForbidden handles this case with default header values.

Forbidden
*/
type APIV1WebhooksDeleteForbidden struct {
}

func (o *APIV1WebhooksDeleteForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/Webhooks][%d] apiV1WebhooksDeleteForbidden ", 403)
}

func (o *APIV1WebhooksDeleteForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAPIV1WebhooksDeleteNotFound creates a APIV1WebhooksDeleteNotFound with default headers values
func NewAPIV1WebhooksDeleteNotFound() *APIV1WebhooksDeleteNotFound {
	return &APIV1WebhooksDeleteNotFound{}
}

/*APIV1WebhooksDeleteNotFound handles this case with default header values.

Not Found
*/
type APIV1WebhooksDeleteNotFound struct {
}

func (o *APIV1WebhooksDeleteNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/Webhooks][%d] apiV1WebhooksDeleteNotFound ", 404)
}

func (o *APIV1WebhooksDeleteNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*APIV1WebhooksDeleteBadRequestBody API v1 webhooks delete bad request body
swagger:model APIV1WebhooksDeleteBadRequestBody
*/
type APIV1WebhooksDeleteBadRequestBody map[string]string

// Validate validates this API v1 webhooks delete bad request body
func (o APIV1WebhooksDeleteBadRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
