// Code generated by go-swagger; DO NOT EDIT.

package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/mluvii/mluvii-api-client/models"
)

// NewAPIV1WebhooksPostParams creates a new APIV1WebhooksPostParams object
// with the default values initialized.
func NewAPIV1WebhooksPostParams() *APIV1WebhooksPostParams {
	var ()
	return &APIV1WebhooksPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAPIV1WebhooksPostParamsWithTimeout creates a new APIV1WebhooksPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAPIV1WebhooksPostParamsWithTimeout(timeout time.Duration) *APIV1WebhooksPostParams {
	var ()
	return &APIV1WebhooksPostParams{

		timeout: timeout,
	}
}

// NewAPIV1WebhooksPostParamsWithContext creates a new APIV1WebhooksPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewAPIV1WebhooksPostParamsWithContext(ctx context.Context) *APIV1WebhooksPostParams {
	var ()
	return &APIV1WebhooksPostParams{

		Context: ctx,
	}
}

// NewAPIV1WebhooksPostParamsWithHTTPClient creates a new APIV1WebhooksPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAPIV1WebhooksPostParamsWithHTTPClient(client *http.Client) *APIV1WebhooksPostParams {
	var ()
	return &APIV1WebhooksPostParams{
		HTTPClient: client,
	}
}

/*APIV1WebhooksPostParams contains all the parameters to send to the API endpoint
for the Api v1 webhooks post operation typically these are written to a http.Request
*/
type APIV1WebhooksPostParams struct {

	/*Model
	  Webhook model

	*/
	Model *models.PublicAPIWebhookModelsWebhookModel

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the Api v1 webhooks post params
func (o *APIV1WebhooksPostParams) WithTimeout(timeout time.Duration) *APIV1WebhooksPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Api v1 webhooks post params
func (o *APIV1WebhooksPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Api v1 webhooks post params
func (o *APIV1WebhooksPostParams) WithContext(ctx context.Context) *APIV1WebhooksPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Api v1 webhooks post params
func (o *APIV1WebhooksPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Api v1 webhooks post params
func (o *APIV1WebhooksPostParams) WithHTTPClient(client *http.Client) *APIV1WebhooksPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Api v1 webhooks post params
func (o *APIV1WebhooksPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithModel adds the model to the Api v1 webhooks post params
func (o *APIV1WebhooksPostParams) WithModel(model *models.PublicAPIWebhookModelsWebhookModel) *APIV1WebhooksPostParams {
	o.SetModel(model)
	return o
}

// SetModel adds the model to the Api v1 webhooks post params
func (o *APIV1WebhooksPostParams) SetModel(model *models.PublicAPIWebhookModelsWebhookModel) {
	o.Model = model
}

// WriteToRequest writes these params to a swagger request
func (o *APIV1WebhooksPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Model != nil {
		if err := r.SetBodyParam(o.Model); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
