// Code generated by go-swagger; DO NOT EDIT.

package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/mluvii/mluvii-api-client/models"
)

// NewAPIV1WebhooksByIDPutParams creates a new APIV1WebhooksByIDPutParams object
// with the default values initialized.
func NewAPIV1WebhooksByIDPutParams() *APIV1WebhooksByIDPutParams {
	var ()
	return &APIV1WebhooksByIDPutParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAPIV1WebhooksByIDPutParamsWithTimeout creates a new APIV1WebhooksByIDPutParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAPIV1WebhooksByIDPutParamsWithTimeout(timeout time.Duration) *APIV1WebhooksByIDPutParams {
	var ()
	return &APIV1WebhooksByIDPutParams{

		timeout: timeout,
	}
}

// NewAPIV1WebhooksByIDPutParamsWithContext creates a new APIV1WebhooksByIDPutParams object
// with the default values initialized, and the ability to set a context for a request
func NewAPIV1WebhooksByIDPutParamsWithContext(ctx context.Context) *APIV1WebhooksByIDPutParams {
	var ()
	return &APIV1WebhooksByIDPutParams{

		Context: ctx,
	}
}

// NewAPIV1WebhooksByIDPutParamsWithHTTPClient creates a new APIV1WebhooksByIDPutParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAPIV1WebhooksByIDPutParamsWithHTTPClient(client *http.Client) *APIV1WebhooksByIDPutParams {
	var ()
	return &APIV1WebhooksByIDPutParams{
		HTTPClient: client,
	}
}

/*APIV1WebhooksByIDPutParams contains all the parameters to send to the API endpoint
for the Api v1 webhooks by Id put operation typically these are written to a http.Request
*/
type APIV1WebhooksByIDPutParams struct {

	/*ID*/
	ID int32
	/*Model*/
	Model *models.PublicAPIWebhookModelsWebhookModel

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the Api v1 webhooks by Id put params
func (o *APIV1WebhooksByIDPutParams) WithTimeout(timeout time.Duration) *APIV1WebhooksByIDPutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Api v1 webhooks by Id put params
func (o *APIV1WebhooksByIDPutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Api v1 webhooks by Id put params
func (o *APIV1WebhooksByIDPutParams) WithContext(ctx context.Context) *APIV1WebhooksByIDPutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Api v1 webhooks by Id put params
func (o *APIV1WebhooksByIDPutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Api v1 webhooks by Id put params
func (o *APIV1WebhooksByIDPutParams) WithHTTPClient(client *http.Client) *APIV1WebhooksByIDPutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Api v1 webhooks by Id put params
func (o *APIV1WebhooksByIDPutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the Api v1 webhooks by Id put params
func (o *APIV1WebhooksByIDPutParams) WithID(id int32) *APIV1WebhooksByIDPutParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the Api v1 webhooks by Id put params
func (o *APIV1WebhooksByIDPutParams) SetID(id int32) {
	o.ID = id
}

// WithModel adds the model to the Api v1 webhooks by Id put params
func (o *APIV1WebhooksByIDPutParams) WithModel(model *models.PublicAPIWebhookModelsWebhookModel) *APIV1WebhooksByIDPutParams {
	o.SetModel(model)
	return o
}

// SetModel adds the model to the Api v1 webhooks by Id put params
func (o *APIV1WebhooksByIDPutParams) SetModel(model *models.PublicAPIWebhookModelsWebhookModel) {
	o.Model = model
}

// WriteToRequest writes these params to a swagger request
func (o *APIV1WebhooksByIDPutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if o.Model != nil {
		if err := r.SetBodyParam(o.Model); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
