// Code generated by go-swagger; DO NOT EDIT.

package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/mluvii/mluvii-api-client/models"
)

// APIV1WebhooksByIDGetReader is a Reader for the APIV1WebhooksByIDGet structure.
type APIV1WebhooksByIDGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *APIV1WebhooksByIDGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewAPIV1WebhooksByIDGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewAPIV1WebhooksByIDGetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewAPIV1WebhooksByIDGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewAPIV1WebhooksByIDGetForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewAPIV1WebhooksByIDGetNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAPIV1WebhooksByIDGetOK creates a APIV1WebhooksByIDGetOK with default headers values
func NewAPIV1WebhooksByIDGetOK() *APIV1WebhooksByIDGetOK {
	return &APIV1WebhooksByIDGetOK{}
}

/*APIV1WebhooksByIDGetOK handles this case with default header values.

Success
*/
type APIV1WebhooksByIDGetOK struct {
	Payload *models.PublicAPIWebhookModelsWebhookModel
}

func (o *APIV1WebhooksByIDGetOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/Webhooks/{id}][%d] apiV1WebhooksByIdGetOK  %+v", 200, o.Payload)
}

func (o *APIV1WebhooksByIDGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PublicAPIWebhookModelsWebhookModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAPIV1WebhooksByIDGetBadRequest creates a APIV1WebhooksByIDGetBadRequest with default headers values
func NewAPIV1WebhooksByIDGetBadRequest() *APIV1WebhooksByIDGetBadRequest {
	return &APIV1WebhooksByIDGetBadRequest{}
}

/*APIV1WebhooksByIDGetBadRequest handles this case with default header values.

Bad Request
*/
type APIV1WebhooksByIDGetBadRequest struct {
	Payload APIV1WebhooksByIDGetBadRequestBody
}

func (o *APIV1WebhooksByIDGetBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v1/Webhooks/{id}][%d] apiV1WebhooksByIdGetBadRequest  %+v", 400, o.Payload)
}

func (o *APIV1WebhooksByIDGetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAPIV1WebhooksByIDGetUnauthorized creates a APIV1WebhooksByIDGetUnauthorized with default headers values
func NewAPIV1WebhooksByIDGetUnauthorized() *APIV1WebhooksByIDGetUnauthorized {
	return &APIV1WebhooksByIDGetUnauthorized{}
}

/*APIV1WebhooksByIDGetUnauthorized handles this case with default header values.

Unauthorized
*/
type APIV1WebhooksByIDGetUnauthorized struct {
}

func (o *APIV1WebhooksByIDGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1/Webhooks/{id}][%d] apiV1WebhooksByIdGetUnauthorized ", 401)
}

func (o *APIV1WebhooksByIDGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAPIV1WebhooksByIDGetForbidden creates a APIV1WebhooksByIDGetForbidden with default headers values
func NewAPIV1WebhooksByIDGetForbidden() *APIV1WebhooksByIDGetForbidden {
	return &APIV1WebhooksByIDGetForbidden{}
}

/*APIV1WebhooksByIDGetForbidden handles this case with default header values.

Forbidden
*/
type APIV1WebhooksByIDGetForbidden struct {
}

func (o *APIV1WebhooksByIDGetForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1/Webhooks/{id}][%d] apiV1WebhooksByIdGetForbidden ", 403)
}

func (o *APIV1WebhooksByIDGetForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAPIV1WebhooksByIDGetNotFound creates a APIV1WebhooksByIDGetNotFound with default headers values
func NewAPIV1WebhooksByIDGetNotFound() *APIV1WebhooksByIDGetNotFound {
	return &APIV1WebhooksByIDGetNotFound{}
}

/*APIV1WebhooksByIDGetNotFound handles this case with default header values.

Not Found
*/
type APIV1WebhooksByIDGetNotFound struct {
}

func (o *APIV1WebhooksByIDGetNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/Webhooks/{id}][%d] apiV1WebhooksByIdGetNotFound ", 404)
}

func (o *APIV1WebhooksByIDGetNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*APIV1WebhooksByIDGetBadRequestBody API v1 webhooks by ID get bad request body
swagger:model APIV1WebhooksByIDGetBadRequestBody
*/
type APIV1WebhooksByIDGetBadRequestBody map[string]string

// Validate validates this API v1 webhooks by ID get bad request body
func (o APIV1WebhooksByIDGetBadRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
