// Code generated by go-swagger; DO NOT EDIT.

package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// APIV1WebhooksByIDPutReader is a Reader for the APIV1WebhooksByIDPut structure.
type APIV1WebhooksByIDPutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *APIV1WebhooksByIDPutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewAPIV1WebhooksByIDPutNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewAPIV1WebhooksByIDPutBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewAPIV1WebhooksByIDPutUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewAPIV1WebhooksByIDPutForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewAPIV1WebhooksByIDPutNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAPIV1WebhooksByIDPutNoContent creates a APIV1WebhooksByIDPutNoContent with default headers values
func NewAPIV1WebhooksByIDPutNoContent() *APIV1WebhooksByIDPutNoContent {
	return &APIV1WebhooksByIDPutNoContent{}
}

/*APIV1WebhooksByIDPutNoContent handles this case with default header values.

Webhook updated
*/
type APIV1WebhooksByIDPutNoContent struct {
}

func (o *APIV1WebhooksByIDPutNoContent) Error() string {
	return fmt.Sprintf("[PUT /api/v1/Webhooks/{id}][%d] apiV1WebhooksByIdPutNoContent ", 204)
}

func (o *APIV1WebhooksByIDPutNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAPIV1WebhooksByIDPutBadRequest creates a APIV1WebhooksByIDPutBadRequest with default headers values
func NewAPIV1WebhooksByIDPutBadRequest() *APIV1WebhooksByIDPutBadRequest {
	return &APIV1WebhooksByIDPutBadRequest{}
}

/*APIV1WebhooksByIDPutBadRequest handles this case with default header values.

Bad Request
*/
type APIV1WebhooksByIDPutBadRequest struct {
	Payload APIV1WebhooksByIDPutBadRequestBody
}

func (o *APIV1WebhooksByIDPutBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/v1/Webhooks/{id}][%d] apiV1WebhooksByIdPutBadRequest  %+v", 400, o.Payload)
}

func (o *APIV1WebhooksByIDPutBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAPIV1WebhooksByIDPutUnauthorized creates a APIV1WebhooksByIDPutUnauthorized with default headers values
func NewAPIV1WebhooksByIDPutUnauthorized() *APIV1WebhooksByIDPutUnauthorized {
	return &APIV1WebhooksByIDPutUnauthorized{}
}

/*APIV1WebhooksByIDPutUnauthorized handles this case with default header values.

Unauthorized
*/
type APIV1WebhooksByIDPutUnauthorized struct {
}

func (o *APIV1WebhooksByIDPutUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /api/v1/Webhooks/{id}][%d] apiV1WebhooksByIdPutUnauthorized ", 401)
}

func (o *APIV1WebhooksByIDPutUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAPIV1WebhooksByIDPutForbidden creates a APIV1WebhooksByIDPutForbidden with default headers values
func NewAPIV1WebhooksByIDPutForbidden() *APIV1WebhooksByIDPutForbidden {
	return &APIV1WebhooksByIDPutForbidden{}
}

/*APIV1WebhooksByIDPutForbidden handles this case with default header values.

Forbidden
*/
type APIV1WebhooksByIDPutForbidden struct {
}

func (o *APIV1WebhooksByIDPutForbidden) Error() string {
	return fmt.Sprintf("[PUT /api/v1/Webhooks/{id}][%d] apiV1WebhooksByIdPutForbidden ", 403)
}

func (o *APIV1WebhooksByIDPutForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAPIV1WebhooksByIDPutNotFound creates a APIV1WebhooksByIDPutNotFound with default headers values
func NewAPIV1WebhooksByIDPutNotFound() *APIV1WebhooksByIDPutNotFound {
	return &APIV1WebhooksByIDPutNotFound{}
}

/*APIV1WebhooksByIDPutNotFound handles this case with default header values.

Not Found
*/
type APIV1WebhooksByIDPutNotFound struct {
}

func (o *APIV1WebhooksByIDPutNotFound) Error() string {
	return fmt.Sprintf("[PUT /api/v1/Webhooks/{id}][%d] apiV1WebhooksByIdPutNotFound ", 404)
}

func (o *APIV1WebhooksByIDPutNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*APIV1WebhooksByIDPutBadRequestBody API v1 webhooks by ID put bad request body
swagger:model APIV1WebhooksByIDPutBadRequestBody
*/
type APIV1WebhooksByIDPutBadRequestBody map[string]string

// Validate validates this API v1 webhooks by ID put bad request body
func (o APIV1WebhooksByIDPutBadRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
