// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/mluvii/publicapi-go/models"
)

// APIV1UsersByIDGetReader is a Reader for the APIV1UsersByIDGet structure.
type APIV1UsersByIDGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *APIV1UsersByIDGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewAPIV1UsersByIDGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewAPIV1UsersByIDGetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewAPIV1UsersByIDGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewAPIV1UsersByIDGetForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewAPIV1UsersByIDGetNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAPIV1UsersByIDGetOK creates a APIV1UsersByIDGetOK with default headers values
func NewAPIV1UsersByIDGetOK() *APIV1UsersByIDGetOK {
	return &APIV1UsersByIDGetOK{}
}

/*APIV1UsersByIDGetOK handles this case with default header values.

Success
*/
type APIV1UsersByIDGetOK struct {
	Payload *models.PublicAPIUserModelsUserModel
}

func (o *APIV1UsersByIDGetOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/Users/{id}][%d] apiV1UsersByIdGetOK  %+v", 200, o.Payload)
}

func (o *APIV1UsersByIDGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PublicAPIUserModelsUserModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAPIV1UsersByIDGetBadRequest creates a APIV1UsersByIDGetBadRequest with default headers values
func NewAPIV1UsersByIDGetBadRequest() *APIV1UsersByIDGetBadRequest {
	return &APIV1UsersByIDGetBadRequest{}
}

/*APIV1UsersByIDGetBadRequest handles this case with default header values.

Bad Request
*/
type APIV1UsersByIDGetBadRequest struct {
	Payload APIV1UsersByIDGetBadRequestBody
}

func (o *APIV1UsersByIDGetBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v1/Users/{id}][%d] apiV1UsersByIdGetBadRequest  %+v", 400, o.Payload)
}

func (o *APIV1UsersByIDGetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAPIV1UsersByIDGetUnauthorized creates a APIV1UsersByIDGetUnauthorized with default headers values
func NewAPIV1UsersByIDGetUnauthorized() *APIV1UsersByIDGetUnauthorized {
	return &APIV1UsersByIDGetUnauthorized{}
}

/*APIV1UsersByIDGetUnauthorized handles this case with default header values.

Unauthorized
*/
type APIV1UsersByIDGetUnauthorized struct {
}

func (o *APIV1UsersByIDGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1/Users/{id}][%d] apiV1UsersByIdGetUnauthorized ", 401)
}

func (o *APIV1UsersByIDGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAPIV1UsersByIDGetForbidden creates a APIV1UsersByIDGetForbidden with default headers values
func NewAPIV1UsersByIDGetForbidden() *APIV1UsersByIDGetForbidden {
	return &APIV1UsersByIDGetForbidden{}
}

/*APIV1UsersByIDGetForbidden handles this case with default header values.

Forbidden
*/
type APIV1UsersByIDGetForbidden struct {
}

func (o *APIV1UsersByIDGetForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1/Users/{id}][%d] apiV1UsersByIdGetForbidden ", 403)
}

func (o *APIV1UsersByIDGetForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAPIV1UsersByIDGetNotFound creates a APIV1UsersByIDGetNotFound with default headers values
func NewAPIV1UsersByIDGetNotFound() *APIV1UsersByIDGetNotFound {
	return &APIV1UsersByIDGetNotFound{}
}

/*APIV1UsersByIDGetNotFound handles this case with default header values.

User ID not found.
*/
type APIV1UsersByIDGetNotFound struct {
}

func (o *APIV1UsersByIDGetNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/Users/{id}][%d] apiV1UsersByIdGetNotFound ", 404)
}

func (o *APIV1UsersByIDGetNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*APIV1UsersByIDGetBadRequestBody API v1 users by ID get bad request body
swagger:model APIV1UsersByIDGetBadRequestBody
*/
type APIV1UsersByIDGetBadRequestBody map[string]string

// Validate validates this API v1 users by ID get bad request body
func (o APIV1UsersByIDGetBadRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
