// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAPIV1UsersByIDGetParams creates a new APIV1UsersByIDGetParams object
// with the default values initialized.
func NewAPIV1UsersByIDGetParams() *APIV1UsersByIDGetParams {
	var ()
	return &APIV1UsersByIDGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAPIV1UsersByIDGetParamsWithTimeout creates a new APIV1UsersByIDGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAPIV1UsersByIDGetParamsWithTimeout(timeout time.Duration) *APIV1UsersByIDGetParams {
	var ()
	return &APIV1UsersByIDGetParams{

		timeout: timeout,
	}
}

// NewAPIV1UsersByIDGetParamsWithContext creates a new APIV1UsersByIDGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewAPIV1UsersByIDGetParamsWithContext(ctx context.Context) *APIV1UsersByIDGetParams {
	var ()
	return &APIV1UsersByIDGetParams{

		Context: ctx,
	}
}

// NewAPIV1UsersByIDGetParamsWithHTTPClient creates a new APIV1UsersByIDGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAPIV1UsersByIDGetParamsWithHTTPClient(client *http.Client) *APIV1UsersByIDGetParams {
	var ()
	return &APIV1UsersByIDGetParams{
		HTTPClient: client,
	}
}

/*APIV1UsersByIDGetParams contains all the parameters to send to the API endpoint
for the Api v1 users by Id get operation typically these are written to a http.Request
*/
type APIV1UsersByIDGetParams struct {

	/*ID
	  User ID

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the Api v1 users by Id get params
func (o *APIV1UsersByIDGetParams) WithTimeout(timeout time.Duration) *APIV1UsersByIDGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Api v1 users by Id get params
func (o *APIV1UsersByIDGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Api v1 users by Id get params
func (o *APIV1UsersByIDGetParams) WithContext(ctx context.Context) *APIV1UsersByIDGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Api v1 users by Id get params
func (o *APIV1UsersByIDGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Api v1 users by Id get params
func (o *APIV1UsersByIDGetParams) WithHTTPClient(client *http.Client) *APIV1UsersByIDGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Api v1 users by Id get params
func (o *APIV1UsersByIDGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the Api v1 users by Id get params
func (o *APIV1UsersByIDGetParams) WithID(id int64) *APIV1UsersByIDGetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the Api v1 users by Id get params
func (o *APIV1UsersByIDGetParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *APIV1UsersByIDGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
