// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// PublicAPISessionModelsSessionModelActivityFile public Api session models session model activity file
// swagger:model PublicApi.Session.Models.SessionModel+ActivityFile
type PublicAPISessionModelsSessionModelActivityFile struct {

	// Operator-owned files only.
	// Company ID.
	CompanyOwner int32 `json:"companyOwner,omitempty"`

	// Name of stored file.
	Name string `json:"name,omitempty"`

	// Operator-owned files only.
	// Operator user ID.
	OperatorOwner int32 `json:"operatorOwner,omitempty"`
}

// Validate validates this public Api session models session model activity file
func (m *PublicAPISessionModelsSessionModelActivityFile) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PublicAPISessionModelsSessionModelActivityFile) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PublicAPISessionModelsSessionModelActivityFile) UnmarshalBinary(b []byte) error {
	var res PublicAPISessionModelsSessionModelActivityFile
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
