// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// PublicAPISessionModelsSessionModelAssignedTag public Api session models session model assigned tag
// swagger:model PublicApi.Session.Models.SessionModel+AssignedTag
type PublicAPISessionModelsSessionModelAssignedTag struct {

	// Name of TAG.
	Name string `json:"name,omitempty"`

	// Operator who assigned the TAG to session.
	UserID int32 `json:"userId,omitempty"`
}

// Validate validates this public Api session models session model assigned tag
func (m *PublicAPISessionModelsSessionModelAssignedTag) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PublicAPISessionModelsSessionModelAssignedTag) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PublicAPISessionModelsSessionModelAssignedTag) UnmarshalBinary(b []byte) error {
	var res PublicAPISessionModelsSessionModelAssignedTag
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
