// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// PublicAPISessionModelsSessionModelReviewerInfo public Api session models session model reviewer info
// swagger:model PublicApi.Session.Models.SessionModel+ReviewerInfo
type PublicAPISessionModelsSessionModelReviewerInfo struct {

	// Freeform textual feedback by reviewer.
	FeedbackText string `json:"feedbackText,omitempty"`

	// first name
	FirstName string `json:"firstName,omitempty"`

	// last name
	LastName string `json:"lastName,omitempty"`

	// user Id
	UserID int32 `json:"userId,omitempty"`

	// user name
	UserName string `json:"userName,omitempty"`
}

// Validate validates this public Api session models session model reviewer info
func (m *PublicAPISessionModelsSessionModelReviewerInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PublicAPISessionModelsSessionModelReviewerInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PublicAPISessionModelsSessionModelReviewerInfo) UnmarshalBinary(b []byte) error {
	var res PublicAPISessionModelsSessionModelReviewerInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
