// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PublicAPISessionModelsSessionModelOperatorInfo Operator information
// swagger:model PublicApi.Session.Models.SessionModel+OperatorInfo
type PublicAPISessionModelsSessionModelOperatorInfo struct {

	// Operator completed After Call Work (submited session conclusion form).
	// Format: date-time
	Concluded strfmt.DateTime `json:"concluded,omitempty"`

	// Selected session result.
	FeedbackResult string `json:"feedbackResult,omitempty"`

	// Freeform textual feedback by operator.
	FeedbackText string `json:"feedbackText,omitempty"`

	// first name
	FirstName string `json:"firstName,omitempty"`

	// joined
	// Format: date-time
	Joined strfmt.DateTime `json:"joined,omitempty"`

	// last name
	LastName string `json:"lastName,omitempty"`

	// Operator left session.
	// Format: date-time
	Left strfmt.DateTime `json:"left,omitempty"`

	// user Id
	UserID int32 `json:"userId,omitempty"`

	// Unique operator username
	UserName string `json:"userName,omitempty"`
}

// Validate validates this public Api session models session model operator info
func (m *PublicAPISessionModelsSessionModelOperatorInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConcluded(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateJoined(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLeft(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PublicAPISessionModelsSessionModelOperatorInfo) validateConcluded(formats strfmt.Registry) error {

	if swag.IsZero(m.Concluded) { // not required
		return nil
	}

	if err := validate.FormatOf("concluded", "body", "date-time", m.Concluded.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *PublicAPISessionModelsSessionModelOperatorInfo) validateJoined(formats strfmt.Registry) error {

	if swag.IsZero(m.Joined) { // not required
		return nil
	}

	if err := validate.FormatOf("joined", "body", "date-time", m.Joined.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *PublicAPISessionModelsSessionModelOperatorInfo) validateLeft(formats strfmt.Registry) error {

	if swag.IsZero(m.Left) { // not required
		return nil
	}

	if err := validate.FormatOf("left", "body", "date-time", m.Left.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PublicAPISessionModelsSessionModelOperatorInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PublicAPISessionModelsSessionModelOperatorInfo) UnmarshalBinary(b []byte) error {
	var res PublicAPISessionModelsSessionModelOperatorInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
