// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// PublicAPIUserModelsUserModel public Api user models user model
// swagger:model PublicApi.User.Models.UserModel
type PublicAPIUserModelsUserModel struct {

	// email
	Email string `json:"email,omitempty"`

	// first name
	FirstName string `json:"firstName,omitempty"`

	// id
	ID int32 `json:"id,omitempty"`

	// last name
	LastName string `json:"lastName,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this public Api user models user model
func (m *PublicAPIUserModelsUserModel) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PublicAPIUserModelsUserModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PublicAPIUserModelsUserModel) UnmarshalBinary(b []byte) error {
	var res PublicAPIUserModelsUserModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
